/**
 * retriever.config.js
 *
 * Configuration constants for the RAG retriever.
 * These values are used when loading the vector store and running similarity search.
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve path to vector-store.json relative to this file's location (src/rag/)
export const backendRoot = path.resolve(__dirname, '..', '..');

export const retrieverConfig = {
  // Path to the saved vector store JSON file (generated by npm run rag:index)
  vectorStorePath: path.resolve(backendRoot, 'storage', 'vector-store.json'),

  // How many top results to return after reranking
  defaultTopK: 5,

  // Minimum similarity score — results below this are discarded
  defaultMinScore: 0.55,

  // Expected embedding vector dimension (Gemini embedding-001 = 3072)
  expectedEmbeddingDimension: 3072,
};
