/**
 * vectorStoreLoader.js
 *
 * Loads the saved LangChain MemoryVectorStore from the JSON file on disk
 * (generated by the indexing pipeline: npm run rag:index).
 *
 * Key behaviors:
 * - Validates vector dimensions and metadata before returning the store.
 * - Caches the loaded store in memory so it is only read from disk once per process.
 * - Throws clear error messages if the file is missing or corrupted.
 *
 * Usage:
 *   import { loadLangChainMemoryVectorStore } from '../rag/vectorStoreLoader.js';
 *   const store = await loadLangChainMemoryVectorStore(filePath, embeddings);
 */

import fs from 'node:fs/promises';
import path from 'node:path';

import { MemoryVectorStore } from '@langchain/classic/vectorstores/memory';

import { retrieverConfig } from './retriever.config.js';

const VECTOR_STORE_TYPE = 'LangChain MemoryVectorStore';

// In-memory cache so we only read from disk once per server process
const vectorStoreCache = new Map();

/**
 * Validates that each stored vector has the correct shape and dimensions.
 * Throws if any vector is malformed.
 */
const validateMemoryVectors = (memoryVectors) => {
  if (!Array.isArray(memoryVectors) || memoryVectors.length === 0) {
    throw new Error('Vector store is empty or missing memoryVectors.');
  }

  const embeddingDimension = memoryVectors[0]?.embedding?.length;

  if (!Number.isInteger(embeddingDimension) || embeddingDimension <= 0) {
    throw new Error('Vector store first embedding is invalid.');
  }

  if (embeddingDimension !== retrieverConfig.expectedEmbeddingDimension) {
    throw new Error(
      `Vector store embedding dimension mismatch. Expected ${retrieverConfig.expectedEmbeddingDimension}, received ${embeddingDimension}.`
    );
  }

  for (const [index, vector] of memoryVectors.entries()) {
    if (typeof vector?.content !== 'string' || !vector.content.trim()) {
      throw new Error(`memoryVectors[${index}] is missing string content.`);
    }
    if (!Array.isArray(vector.embedding) || vector.embedding.length === 0) {
      throw new Error(`memoryVectors[${index}] is missing embedding values.`);
    }
    if (vector.embedding.length !== embeddingDimension) {
      throw new Error(
        `memoryVectors[${index}] has dimension ${vector.embedding.length}; expected ${embeddingDimension}.`
      );
    }
    if (!vector.embedding.every((value) => Number.isFinite(value))) {
      throw new Error(`memoryVectors[${index}] contains non-numeric embedding values.`);
    }
    if (!vector.metadata || typeof vector.metadata !== 'object') {
      throw new Error(`memoryVectors[${index}] is missing metadata.`);
    }
  }

  return embeddingDimension;
};

const loadVectorStorePayload = async (filePath) => {
  const absoluteFilePath = path.resolve(filePath);
  let rawJson;

  try {
    rawJson = await fs.readFile(absoluteFilePath, 'utf8');
  } catch (error) {
    if (error?.code === 'ENOENT') {
      throw new Error(`Vector store file not found at ${absoluteFilePath}. Run npm run rag:index first.`);
    }
    throw new Error(`Unable to read vector store file at ${absoluteFilePath}: ${error.message}`);
  }

  try {
    return JSON.parse(rawJson);
  } catch (error) {
    throw new Error(`Vector store JSON is invalid at ${absoluteFilePath}: ${error.message}`);
  }
};

/**
 * Loads and returns the LangChain MemoryVectorStore.
 * Results are cached: the file is only read from disk once per process.
 *
 * @param {string} filePath   - Path to the vector-store.json file
 * @param {object} embeddings - LangChain embeddings instance (used for query embedding at search time)
 * @returns {{ vectorStore, metadata, totalVectors, embeddingDimension }}
 */
export const loadLangChainMemoryVectorStore = async (filePath, embeddings) => {
  const absoluteFilePath = path.resolve(filePath);

  // Return cached promise if already loaded
  if (vectorStoreCache.has(absoluteFilePath)) {
    return vectorStoreCache.get(absoluteFilePath);
  }

  const loadPromise = (async () => {
    const payload = await loadVectorStorePayload(absoluteFilePath);

    if (payload.vectorStoreType !== VECTOR_STORE_TYPE) {
      throw new Error(
        `Unsupported vector store type "${payload.vectorStoreType}". Expected "${VECTOR_STORE_TYPE}".`
      );
    }

    const embeddingDimension = validateMemoryVectors(payload.memoryVectors);
    const vectorStore = new MemoryVectorStore(embeddings);

    // Hydrate MemoryVectorStore from saved vectors — no re-embedding needed.
    // Depends on memoryVectors being a settable public array on @langchain/classic@1.0.32.
    // Package is pinned to exact version in package.json. Do NOT add ^ caret.
    // If this guard throws after a package update, check @langchain/classic changelog.
    vectorStore.memoryVectors = payload.memoryVectors;
    if (!Array.isArray(vectorStore.memoryVectors) || vectorStore.memoryVectors.length !== payload.memoryVectors.length) {
      throw new Error(
        '[vectorStoreLoader] Failed to hydrate MemoryVectorStore.memoryVectors. ' +
        '@langchain/classic may have changed its internal API. ' +
        'Package must stay pinned to 1.0.32 in package.json.'
      );
    }

    return {
      vectorStore,
      metadata: payload,
      totalVectors: payload.memoryVectors.length,
      embeddingDimension,
    };
  })();

  vectorStoreCache.set(absoluteFilePath, loadPromise);

  try {
    return await loadPromise;
  } catch (error) {
    // Remove from cache so next call retries the file load
    vectorStoreCache.delete(absoluteFilePath);
    throw error;
  }
};
